name: Run Python Script

on:
  schedule:
    # This line runs the workflow at 00:00 UTC every Sunday
    - cron: "0 0 * * 0"

  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Retry Step
        uses: nick-fields/retry@v2.8.3
        id: retry
        with:
          timeout_seconds: 15
          max_attempts: 3
          command: python main.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}